### ISSUE TITLE
Unsupported watchOS version/package description version

### ISSUE THREAD

**Issue by RobinDaugherty** [onmyway133/DeepDiff#64]
> invalidManifestFormat("/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/TemporaryFile.rCB6P4.swift:11:19: error: \'v6\' is unavailable\n        .watchOS(.v6)\n                  ^~\nPackageDescription.SupportedPlatform:45:27: note: \'v6\' was introduced in PackageDescription 5.1\n        public static var v6: PackageDescription.SupportedPlatform.WatchOSVersion\n                          ^", diagnosticFile: Optional(<AbsolutePath:"/Users/vagrant/Library/Developer/Xcode/DerivedData/Harper-cxngxloxijxbllfwrovkiaxoqvem/SourcePackages/ManifestLoading/deepdiff.dia">)) in https://github.com/onmyway133/DeepDiff

Introduced in 2.3.2.

Caused by this change: https://github.com/onmyway133/DeepDiff/commit/86d6b51b47804e380801f4eba45297cb07788b18#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR11

I'm not getting this on all versions of Xcode. For example, it's working on Xcode 12.5 RC on my machine. But it fails consistently on Bitrise with Xcode 12.4 and 12.5.

**Comment by onmyway133** [comment]
@RobinDaugherty sorry about that, I think this PR https://github.com/onmyway133/DeepDiff/pull/65 should fix it

**Comment by adamayoung** [comment]
Any idea when you'll make a release with PR #65 ?

**Comment by onmyway133** [comment]
@adamayoung Hi, you can check release 3.2.3 https://github.com/onmyway133/DeepDiff/releases/tag/3.2.3
